services:
  app:
    build: .
    container_name: doceteria_fastapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app  # útil em dev (atualiza código em tempo real)
    depends_on:
      - redis
    command: >
      uv run uvicorn src.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  redis:
    image: redis:7.4-alpine
    container_name: fastapi_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
