"""Alterado campo de pedido de items para itens_pedido

Revision ID: 18e8c76970b3
Revises: 6bb175712622
Create Date: 2025-10-22 14:55:20.340256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e8c76970b3'
down_revision: Union[str, Sequence[str], None] = '6bb175712622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
