"""Alterado relacao em items de items para itens_pedido

Revision ID: 3735e72715d2
Revises: 18e8c76970b3
Create Date: 2025-10-22 15:07:01.793978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3735e72715d2'
down_revision: Union[str, Sequence[str], None] = '18e8c76970b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
