"""alter table items column preco_total for preco_unitario

Revision ID: 3b57bcd20b86
Revises: 2b5731781267
Create Date: 2025-10-22 14:46:57.230864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b57bcd20b86'
down_revision: Union[str, Sequence[str], None] = '2b5731781267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedido', sa.Column('preco_unitario', sa.Float(), nullable=False))
    op.drop_column('itens_pedido', 'preco_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedido', sa.Column('preco_total', sa.FLOAT(), nullable=False))
    op.drop_column('itens_pedido', 'preco_unitario')
    # ### end Alembic commands ###
