"""Alterado foreign da tabela Item e Pedido

Revision ID: 6bb175712622
Revises: 3b57bcd20b86
Create Date: 2025-10-22 14:54:05.680430

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bb175712622"
down_revision: Union[str, Sequence[str], None] = "3b57bcd20b86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
